import { describe, expect, it } from "vitest";
import {
  initializeGitRepository,
  readGitIdentity,
  type ExecRunner,
} from "./git.js";

describe("readGitIdentity", () => {
  it("returns configured name and email", async () => {
    const execRunner = createExecRunner({
      "git config user.name": { stdout: "Agent Builder\n", stderr: "" },
      "git config user.email": { stdout: "builder@example.com\n", stderr: "" },
    });

    await expect(readGitIdentity(execRunner, "/tmp/agent")).resolves.toEqual({
      name: "Agent Builder",
      email: "builder@example.com",
    });
  });
});

describe("initializeGitRepository", () => {
  it("skips the initial commit when git identity is missing", async () => {
    const calls: string[] = [];
    const execRunner = createExecRunner(
      {
        "git init": { stdout: "", stderr: "" },
        "git add .": { stdout: "", stderr: "" },
      },
      calls,
    );

    const result = await initializeGitRepository(execRunner, "/tmp/agent");

    expect(result).toEqual({
      committed: false,
      missingIdentity: ["user.name", "user.email"],
    });
    expect(calls).not.toContain(
      'git commit -m "Initial commit (generated by agent-dev-kit)"',
    );
  });

  it("creates the initial commit when git identity is configured", async () => {
    const calls: string[] = [];
    const execRunner = createExecRunner(
      {
        "git init": { stdout: "", stderr: "" },
        "git add .": { stdout: "", stderr: "" },
        "git config user.name": { stdout: "Agent Builder\n", stderr: "" },
        "git config user.email": {
          stdout: "builder@example.com\n",
          stderr: "",
        },
        'git commit -m "Initial commit (generated by agent-dev-kit)"': {
          stdout: "[main] Initial commit\n",
          stderr: "",
        },
      },
      calls,
    );

    const result = await initializeGitRepository(execRunner, "/tmp/agent");

    expect(result).toEqual({
      committed: true,
      missingIdentity: [],
    });
    expect(calls).toContain(
      'git commit -m "Initial commit (generated by agent-dev-kit)"',
    );
  });
});

function createExecRunner(
  responses: Record<string, { stdout: string; stderr: string }>,
  calls: string[] = [],
): ExecRunner {
  return async (command) => {
    calls.push(command);

    const response = responses[command];
    if (!response) {
      throw new Error(`Command failed: ${command}`);
    }

    return response;
  };
}
