export interface ExecResult {
  stdout: string;
  stderr: string;
}

export interface ExecOptions {
  cwd?: string;
}

export type ExecRunner = (
  command: string,
  options?: ExecOptions,
) => Promise<ExecResult>;

export interface GitIdentity {
  name?: string;
  email?: string;
}

export interface GitInitializationResult {
  committed: boolean;
  missingIdentity: Array<"user.name" | "user.email">;
}

async function readGitConfigValue(
  execRunner: ExecRunner,
  cwd: string,
  key: "user.name" | "user.email",
): Promise<string | undefined> {
  try {
    const { stdout } = await execRunner(`git config ${key}`, { cwd });
    const value = stdout.trim();
    return value === "" ? undefined : value;
  } catch {
    return undefined;
  }
}

export async function readGitIdentity(
  execRunner: ExecRunner,
  cwd: string,
): Promise<GitIdentity> {
  const [name, email] = await Promise.all([
    readGitConfigValue(execRunner, cwd, "user.name"),
    readGitConfigValue(execRunner, cwd, "user.email"),
  ]);

  return { name, email };
}

export async function initializeGitRepository(
  execRunner: ExecRunner,
  cwd: string,
): Promise<GitInitializationResult> {
  await execRunner("git init", { cwd });
  await execRunner("git add .", { cwd });

  const identity = await readGitIdentity(execRunner, cwd);
  const missingIdentity: Array<"user.name" | "user.email"> = [];

  if (!identity.name) {
    missingIdentity.push("user.name");
  }

  if (!identity.email) {
    missingIdentity.push("user.email");
  }

  if (missingIdentity.length > 0) {
    return {
      committed: false,
      missingIdentity,
    };
  }

  await execRunner(
    'git commit -m "Initial commit (generated by agent-dev-kit)"',
    {
      cwd,
    },
  );

  return {
    committed: true,
    missingIdentity: [],
  };
}
