#!/usr/bin/env node
import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import chalk from 'chalk';
import {
  type AgentEntrypoint,
  FILENAME,
  generateManifest,
  validateManifest,
} from './lib';

export interface GenerateOptions {
  dir: string;
  project?: string;
  force?: boolean;
}

export interface ValidateOptions {
  dir: string;
}

export interface ShowOptions {
  dir: string;
}

export function handleGenerate(opts: GenerateOptions): void {
  const dir = path.resolve(opts.dir);
  const outFile = path.join(dir, FILENAME);

  if (fs.existsSync(outFile) && !opts.force) {
    console.log(chalk.yellow(`⚠  ${FILENAME} already exists. Use --force to overwrite.`));
    process.exit(1);
  }

  const manifest = generateManifest(dir, opts.project);
  const content =
    `# AGENT_ENTRYPOINT.yaml\n# Generated by agent-entrypoint CLI\n# Edit this file to reflect operational reality.\n\n` +
    yaml.dump(manifest, { lineWidth: 80 });

  fs.writeFileSync(outFile, content, 'utf-8');
  console.log(chalk.green(`✅ Generated ${outFile}`));
  console.log(chalk.gray('\nReview and update:'));
  console.log(chalk.gray(`  - components: add missing services`));
  console.log(chalk.gray(`  - first_checks: add environment-specific checks`));
  console.log(chalk.gray(`  - do_not_assume: document common pitfalls`));
}

export function handleValidate(opts: ValidateOptions): void {
  const dir = path.resolve(opts.dir);
  const result = validateManifest(dir);

  if (!result.valid) {
    if (result.issues[0]?.includes('not found')) {
      console.log(chalk.red(`✗ ${FILENAME} not found in ${dir}`));
      console.log(chalk.gray(`  Run: agent-entrypoint generate --dir ${dir}`));
      process.exit(1);
    }
    if (result.issues[0]?.startsWith('YAML parse error')) {
      console.log(chalk.red(`✗ ${result.issues[0]}`));
      process.exit(1);
    }
    console.log(chalk.red(`✗ Validation failed (${result.issues.length} issue(s)):`));
    result.issues.forEach((i) => console.log(chalk.yellow(`  - ${i}`)));
    process.exit(1);
  }

  const manifest = result.manifest!;
  console.log(chalk.green(`✅ ${FILENAME} is valid`));
  console.log(chalk.cyan(`   Project: ${manifest.project}`));
  console.log(
    chalk.cyan(`   Components: ${(manifest.components || []).map((c) => c.name).join(', ')}`),
  );
}

export function handleShow(opts: ShowOptions): void {
  const dir = path.resolve(opts.dir);
  const filePath = path.join(dir, FILENAME);

  if (!fs.existsSync(filePath)) {
    console.log(chalk.red(`✗ ${FILENAME} not found`));
    process.exit(1);
  }

  const manifest = yaml.load(fs.readFileSync(filePath, 'utf-8')) as AgentEntrypoint;

  console.log(chalk.bold.cyan(`\n📋 ${manifest.project}\n`));
  console.log(chalk.bold('📄 Primary Docs:'));
  (manifest.primary_docs || []).forEach((d) => console.log(`  - ${d}`));
  console.log(chalk.bold('\n🔧 Components:'));
  (manifest.components || []).forEach((c) =>
    console.log(`  - ${chalk.yellow(c.name)}: ${c.role}`),
  );
  console.log(chalk.bold('\n✅ First Checks:'));
  (manifest.first_checks || []).forEach((c) => console.log(`  - ${c}`));
  console.log(chalk.bold('\n⛔ Do Not Assume:'));
  (manifest.do_not_assume || []).forEach((a) => console.log(`  - ${chalk.red(a)}`));
  console.log(chalk.bold('\n📌 Authoritative Sources:'));
  (manifest.authoritative_sources || []).forEach((s) => console.log(`  - ${s}`));
  console.log();
}

export interface CliHandlers {
  generate?: typeof handleGenerate;
  validate?: typeof handleValidate;
  show?: typeof handleShow;
}

export function buildProgram(handlers: CliHandlers = {}): Command {
  const generate = handlers.generate ?? handleGenerate;
  const validate = handlers.validate ?? handleValidate;
  const show = handlers.show ?? handleShow;

  const program = new Command();

  program
    .name('agent-entrypoint')
    .description('Generate and validate AGENT_ENTRYPOINT.yaml for agent-friendly repo navigation')
    .version('1.0.0');

  program
    .command('generate')
    .alias('gen')
    .description(`Generate ${FILENAME} for a repo`)
    .option('-d, --dir <path>', 'Target repo directory', '.')
    .option('-p, --project <name>', 'Project name (default: directory name)')
    .option('--force', 'Overwrite existing file')
    .action((opts: GenerateOptions) => generate(opts));

  program
    .command('validate')
    .alias('check')
    .description(`Validate ${FILENAME} in a repo`)
    .option('-d, --dir <path>', 'Target repo directory', '.')
    .action((opts: ValidateOptions) => validate(opts));

  program
    .command('show')
    .description(`Display ${FILENAME} in a readable format`)
    .option('-d, --dir <path>', 'Target repo directory', '.')
    .action((opts: ShowOptions) => show(opts));

  return program;
}

if (require.main === module) {
  buildProgram().parse();
}
