#!/usr/bin/env node
import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import chalk from 'chalk';

const program = new Command();

interface Component {
  name: string;
  role: string;
}

interface AgentEntrypoint {
  project: string;
  primary_docs: string[];
  components: Component[];
  first_checks: string[];
  do_not_assume: string[];
  authoritative_sources: string[];
}

const FILENAME = 'AGENT_ENTRYPOINT.yaml';

function detectDocs(dir: string): string[] {
  const candidates = ['README.md', 'ARCHITECTURE.md', 'docs/architecture.md', 'CONTRIBUTING.md', 'AGENTS.md'];
  return candidates.filter(f => fs.existsSync(path.join(dir, f)));
}

function detectComponents(dir: string): Component[] {
  const components: Component[] = [];
  // Check for common patterns
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('.') || entry.name === 'node_modules' || entry.name === 'dist') continue;
    const name = entry.name;
    let role = 'module';
    if (name.includes('api') || name.includes('server')) role = 'api server';
    else if (name.includes('web') || name.includes('ui') || name.includes('frontend') || name.includes('app')) role = 'frontend';
    else if (name.includes('agent')) role = 'agent';
    else if (name.includes('cli')) role = 'cli tool';
    else if (name.includes('lib') || name.includes('core') || name.includes('shared')) role = 'shared library';
    components.push({ name, role });
  }
  return components.slice(0, 6); // cap at 6
}

function detectStartCommands(dir: string): string[] {
  const checks: string[] = [];
  if (fs.existsSync(path.join(dir, 'package.json'))) {
    checks.push('npm install && npm run build');
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf-8'));
    if (pkg.scripts?.dev) checks.push('npm run dev');
    if (pkg.scripts?.start) checks.push('npm start');
  }
  if (fs.existsSync(path.join(dir, 'Makefile'))) checks.push('make');
  if (fs.existsSync(path.join(dir, 'docker-compose.yml')) || fs.existsSync(path.join(dir, 'docker-compose.yaml')))
    checks.push('docker compose up');
  if (checks.length === 0) checks.push('check README.md for start instructions');
  return checks;
}

// ── generate ─────────────────────────────────────────────────────────────────
program
  .command('generate')
  .alias('gen')
  .description(`Generate ${FILENAME} for a repo`)
  .option('-d, --dir <path>', 'Target repo directory', '.')
  .option('-p, --project <name>', 'Project name (default: directory name)')
  .option('--force', 'Overwrite existing file')
  .action((opts) => {
    const dir = path.resolve(opts.dir);
    const outFile = path.join(dir, FILENAME);

    if (fs.existsSync(outFile) && !opts.force) {
      console.log(chalk.yellow(`⚠  ${FILENAME} already exists. Use --force to overwrite.`));
      process.exit(1);
    }

    const projectName = opts.project || path.basename(dir);
    const docs = detectDocs(dir);
    const components = detectComponents(dir);
    const startChecks = detectStartCommands(dir);

    const manifest: AgentEntrypoint = {
      project: projectName,
      primary_docs: docs.length > 0 ? docs : ['README.md'],
      components: components.length > 0 ? components : [{ name: projectName, role: 'main module' }],
      first_checks: [
        ...startChecks,
        'verify all required env vars are set',
        'check logs for startup errors',
      ],
      do_not_assume: [
        'environment matches local dev',
        'default config is correct',
        'dependencies are already installed',
      ],
      authoritative_sources: docs.length > 0 ? docs.slice(0, 2) : ['README.md'],
    };

    const content = `# AGENT_ENTRYPOINT.yaml\n# Generated by agent-entrypoint CLI\n# Edit this file to reflect operational reality.\n\n` +
      yaml.dump(manifest, { lineWidth: 80 });

    fs.writeFileSync(outFile, content, 'utf-8');
    console.log(chalk.green(`✅ Generated ${outFile}`));
    console.log(chalk.gray('\nReview and update:'));
    console.log(chalk.gray(`  - components: add missing services`));
    console.log(chalk.gray(`  - first_checks: add environment-specific checks`));
    console.log(chalk.gray(`  - do_not_assume: document common pitfalls`));
  });

// ── validate ──────────────────────────────────────────────────────────────────
program
  .command('validate')
  .alias('check')
  .description(`Validate ${FILENAME} in a repo`)
  .option('-d, --dir <path>', 'Target repo directory', '.')
  .action((opts) => {
    const dir = path.resolve(opts.dir);
    const filePath = path.join(dir, FILENAME);

    if (!fs.existsSync(filePath)) {
      console.log(chalk.red(`✗ ${FILENAME} not found in ${dir}`));
      console.log(chalk.gray(`  Run: agent-entrypoint generate --dir ${dir}`));
      process.exit(1);
    }

    let manifest: Partial<AgentEntrypoint>;
    try {
      manifest = yaml.load(fs.readFileSync(filePath, 'utf-8')) as Partial<AgentEntrypoint>;
    } catch (e) {
      console.log(chalk.red(`✗ YAML parse error: ${e}`));
      process.exit(1);
    }

    const issues: string[] = [];
    const required: Array<keyof AgentEntrypoint> = [
      'project', 'primary_docs', 'components', 'first_checks', 'do_not_assume', 'authoritative_sources'
    ];
    for (const field of required) {
      if (!manifest[field]) issues.push(`Missing field: ${field}`);
    }

    // Check referenced docs exist
    for (const doc of manifest.primary_docs || []) {
      if (!fs.existsSync(path.join(dir, doc))) {
        issues.push(`primary_docs: '${doc}' does not exist`);
      }
    }

    if (issues.length === 0) {
      console.log(chalk.green(`✅ ${FILENAME} is valid`));
      console.log(chalk.cyan(`   Project: ${manifest.project}`));
      console.log(chalk.cyan(`   Components: ${(manifest.components || []).map(c => c.name).join(', ')}`));
    } else {
      console.log(chalk.red(`✗ Validation failed (${issues.length} issue(s)):`));
      issues.forEach(i => console.log(chalk.yellow(`  - ${i}`)));
      process.exit(1);
    }
  });

// ── show ──────────────────────────────────────────────────────────────────────
program
  .command('show')
  .description(`Display ${FILENAME} in a readable format`)
  .option('-d, --dir <path>', 'Target repo directory', '.')
  .action((opts) => {
    const dir = path.resolve(opts.dir);
    const filePath = path.join(dir, FILENAME);

    if (!fs.existsSync(filePath)) {
      console.log(chalk.red(`✗ ${FILENAME} not found`));
      process.exit(1);
    }

    const manifest = yaml.load(fs.readFileSync(filePath, 'utf-8')) as AgentEntrypoint;

    console.log(chalk.bold.cyan(`\n📋 ${manifest.project}\n`));
    console.log(chalk.bold('📄 Primary Docs:'));
    (manifest.primary_docs || []).forEach(d => console.log(`  - ${d}`));
    console.log(chalk.bold('\n🔧 Components:'));
    (manifest.components || []).forEach(c => console.log(`  - ${chalk.yellow(c.name)}: ${c.role}`));
    console.log(chalk.bold('\n✅ First Checks:'));
    (manifest.first_checks || []).forEach(c => console.log(`  - ${c}`));
    console.log(chalk.bold('\n⛔ Do Not Assume:'));
    (manifest.do_not_assume || []).forEach(a => console.log(`  - ${chalk.red(a)}`));
    console.log(chalk.bold('\n📌 Authoritative Sources:'));
    (manifest.authoritative_sources || []).forEach(s => console.log(`  - ${s}`));
    console.log();
  });

program
  .name('agent-entrypoint')
  .description('Generate and validate AGENT_ENTRYPOINT.yaml for agent-friendly repo navigation')
  .version('1.0.0');

program.parse();
